### ISSUE TITLE
Add a link to the article

### ISSUE THREAD

**Issue by volenpopov** [lmammino/s3-presigned-urls-examples#1]
I recommend adding a link to your article ([The illustrated guide to S3 pre-signed URLs](https://fourtheorem.com/the-illustrated-guide-to-s3-pre-signed-urls/)) in the repository's README. It contains a ton of useful information and explanations related to the code examples and would definitely be useful to anyone who stumbles upon the repo, but is not aware that the article exists.

**Comment by lmammino** [comment]
Thanks a million for the suggestion. I created the examples before the article and then i forgot to link it back :)

Closed by 30d2745
